Repository ironcore-dev/ironcore-net, pull requests merged in 2023-09, with the labels that each got.

#169 Implement and use topology labels
  api/core/v1alpha1/loadbalancer_types.go
  api/core/v1alpha1/well_known_labels.go
  apinetlet/controllers/loadbalancer_controller.go
  apinetlet/controllers/loadbalancer_controller_test.go
  client-go/applyconfigurations/core/v1alpha1/loadbalancerspec.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/api_violations.report
  client-go/openapi/zz_generated.openapi.go
  cmd/metalnetlet/main.go
  go.sum
  internal/apis/core/well_known_labels.go
  metalnetlet/controllers/controllers_suite_test.go
  metalnetlet/controllers/metalnetnode_controller.go
  metalnetlet/controllers/metalnetnode_controller_test.go
Labels: enhancement, size/M

#170 Fix rbac permissions
  Makefile
  config/apiserver/rbac/apinetlet_bootstrapper_role.yaml
  config/apiserver/rbac/apinetlet_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/apinetlet_role.yaml
  config/apiserver/rbac/apinetlet_rolebinding.yaml
  config/apiserver/rbac/apiserver_role.yaml
  config/apiserver/rbac/bucketpool_role.yaml
  config/apiserver/rbac/kustomization.yaml
  config/apiserver/rbac/machinepool_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/machinepool_role.yaml
  config/apiserver/rbac/metalnetlet_bootstrapper_role.yaml
  config/apiserver/rbac/metalnetlet_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/metalnetlet_role.yaml
  config/apiserver/rbac/metalnetlet_rolebinding.yaml
  config/apiserver/rbac/networkplugin_bootstrapper_role.yaml
  config/apiserver/rbac/networkplugin_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/networkplugin_role.yaml
  config/apiserver/rbac/networkplugin_rolebinding.yaml
  config/apiserver/rbac/volumepool_bootstrapper_role.yaml
  config/apiserver/rbac/volumepool_role.yaml
  config/apiserver/rbac/volumepool_rolebinding.yaml
  config/onmetal-api-net/rbac/role.yaml
Labels: bug, size/XL

#171 Fix superfluous rbac
  config/controller/manager/manager.yaml
  config/controller/rbac/apinetlet_bootstrapper_role.yaml
  config/controller/rbac/apinetlet_bootstrapper_rolebinding.yaml
  config/controller/rbac/apinetlet_role.yaml
  config/controller/rbac/apinetlet_rolebinding.yaml
  config/controller/rbac/kustomization.yaml
  config/controller/rbac/metalnetlet_bootstrapper_role.yaml
  config/controller/rbac/metalnetlet_bootstrapper_rolebinding.yaml
  config/controller/rbac/metalnetlet_role.yaml
  config/controller/rbac/metalnetlet_rolebinding.yaml
  hack/replace.sh
  hack/validate-kustomize.sh
Labels: bug, size/L

#173 Implement validation for core types
  apinetlet/controllers/networkinterface_controller_test.go
  config/apiserver/apiservice/bases/v1alpha1.core.apinet.api.onmetal.de.yaml
  internal/apis/core/validation/common.go
  internal/apis/core/validation/instance.go
  internal/apis/core/validation/ip.go
  internal/apis/core/validation/ipaddress.go
  internal/apis/core/validation/loadbalancer.go
  internal/apis/core/validation/natgateway.go
  internal/apis/core/validation/natgatewayautoscaler.go
  internal/apis/core/validation/network.go
  internal/apis/core/validation/networkid.go
  internal/apis/core/validation/networkinterface.go
  internal/app/core_test.go
Labels: enhancement, size/L

#174 Fix metalnet network interface source key labels
  metalnetlet/controllers/networkinterface_controller.go
Labels: bug, size/XS

#175 Docs about network & ip lifecycle
  README.md
  docs/concepts/README.md
  docs/concepts/ip-lifecycle.md
  docs/concepts/network-lifecycle.md
  docs/concepts/objects.md
Labels: documentation, size/L

#176 Document `apinetlet` <-> `onmetal-api` integration
  docs/concepts/README.md
  docs/concepts/onmetal-api-integration.md
Labels: documentation, size/M

#177 Fix scheduler, nic nat release, metalnet instances
  api/core/v1alpha1/networkinterface_types.go
  cmd/controller-manager/main.go
  internal/apis/core/networkinterface_types.go
  internal/controllers/controllers_suite_test.go
  internal/controllers/daemonset_controller.go
  internal/controllers/daemonset_controller_test.go
  internal/controllers/ipaddressgc_controller.go
  internal/controllers/networkidgc_controller.go
  internal/controllers/networkinterfacenatrelease_controller.go
  internal/controllers/networkinterfacenatrelease_controller_test.go
  internal/controllers/scheduler_controller.go
  metalnetlet/controllers/instance_controller.go
  metalnetlet/controllers/instance_controller_test.go
  utils/handler/expectations.go
Labels: bug, size/L

#179 Bump metalnet v0.1.8
  go.mod
  go.sum
  metalnetlet/controllers/conversion.go
  metalnetlet/controllers/networkinterface_controller.go
Labels: enhancement, size/S
