Repository ironcore-dev/ironcore-net, pull requests merged in 2023-12, with the labels that each got.

#187 Switch to `ironcore-dev/metalnet`
  .github/workflows/lint.yml
  .github/workflows/publish-docker.yml
  .github/workflows/test.yml
  Dockerfile
  Makefile
  cmd/metalnetlet/main.go
  config/metalnetlet/rbac/role.yaml
  docs/api-reference/core.md
  go.mod
  go.sum
  hack/api-reference/config.json
  hack/api-reference/template/members.tpl
  hack/api-reference/template/pkg.tpl
  hack/api-reference/template/placeholder.go
  hack/api-reference/template/type.tpl
  hack/setup-git-redirect.sh
  metalnetlet/controllers/controllers_suite_test.go
  metalnetlet/controllers/conversion.go
  metalnetlet/controllers/instance_controller.go
  metalnetlet/controllers/instance_controller_test.go
  metalnetlet/controllers/metalnetnode_controller.go
  metalnetlet/controllers/network_controller.go
  metalnetlet/controllers/network_controller_test.go
  metalnetlet/controllers/networkinterface_controller.go
  metalnetlet/controllers/networkinterface_controller_test.go
Labels: documentation, enhancement, size/XXL, breaking, ok-to-image

#188 Fix docker build
  .github/workflows/publish-docker.yml
  Dockerfile
Labels: bug, size/XS, ok-to-image

#189 Fix build and run refs in `Makefile`
  Makefile
Labels: bug, size/S

#199 Fix wrong `ClusterRoleBinding` for bootstrap token
  config/apiserver/rbac/apinetlet_bootstrapper_rolebinding.yaml
  config/apiserver/rbac/metalnetlet_bootstrapper_rolebinding.yaml
Labels: bug, size/XS
