Repository ironcore-dev/ironcore-net, pull requests merged in 2024-10, with the labels that each got.

#327 Add partition wise network peering status in apinet `Network` resource
  api/core/v1alpha1/network_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  apinetlet/controllers/conversion.go
  apinetlet/controllers/network_controller.go
  apinetlet/controllers/network_controller_test.go
  client-go/applyconfigurations/core/v1alpha1/networkstatus.go
  client-go/applyconfigurations/internal/internal.go
  client-go/openapi/api_violations.report
  client-go/openapi/zz_generated.openapi.go
  docs/api-reference/core.md
  internal/apis/core/network_types.go
  internal/apis/core/v1alpha1/zz_generated.conversion.go
  internal/apis/core/zz_generated.deepcopy.go
  metalnetlet/controllers/network_controller.go
  metalnetlet/controllers/network_controller_test.go
Labels: bug, documentation, size/L

#332 Bump `ironcore` to v0.2.0
  go.mod
  go.sum
Labels: enhancement, size/M

#333 Fix in-cluster leader election in `apinetlet`
  cmd/apinetlet/main.go
Labels: bug, size/XS
