Repository ironcore-dev/ironcore-net, pull requests merged in 2024-01, with the labels that each got.

#203 Fix namespace deletion due to lacking protobuf
  internal/apiserver/apiserver.go
  internal/serializer/serializer.go
Labels: bug, size/M

#209 Add print column for `Prefixes` in `NetworkInterface`
  internal/registry/networkinterface/tableconvertor.go
Labels: bug, enhancement, size/S

#211 Switch to `enable-priority-and-fairness` flag in `apiserver` deployment
  config/apiserver/server/server.yaml
Labels: bug, size/XS

#213 Switch to `enable-priority-and-fairness` flag in `apiserver` kustomize patches
  config/apiserver/default/apiserver_certificate_patch.yaml
  config/apiserver/etcdless/apiserver_certificate_patch.yaml
Labels: bug, size/XS

#224 Fix `namePrefix` for `etcdless` kustomize configuration
  config/apiserver/etcdless/kustomization.yaml
Labels: bug, size/XS
