Repository ironcore-dev/ironcore-net, pull requests merged in 2024-02, with the labels that each got.

#228 Fix installation of apiservice in `Makefile`
  Makefile
Labels: bug, size/M

#230 Fix nil pointer for internal LB type handling in api server
  internal/controllers/loadbalancer_controller_test.go
  internal/registry/loadbalancer/storage.go
Labels: bug, size/M

#231 Fix internal `LoadBalancer` creation
  apinetlet/controllers/loadbalancer_controller_test.go
  internal/registry/loadbalancer/storage.go
Labels: bug, size/L

#232 Bump `golangci-lint` to v1.55.2 in GH workflow
  .github/workflows/lint.yml
Labels: size/XS, chore

#234 Bump `golang` to 1.22 and `golangci-lint` to 1.56.0
  .github/release-drafter.yml
  .github/workflows/lint.yml
  Makefile
  go.mod
Labels: size/S, chore

#235 Add reuse workflow
  .github/workflows/reuse.yml
Labels: size/S, chore

#241 Fix NATReconciler to modify NATTable of NIC belonging to NATs Network
  cmd/controller-manager/main.go
  internal/client/client.go
  internal/controllers/controllers_suite_test.go
  internal/controllers/natgateway_controller.go
  internal/controllers/natgateway_controller_test.go
Labels: bug, size/M

#240 Add development setup document and modify config files as needed
  Makefile
  config/apinetlet/default/kustomization.yaml
  config/apinetlet/kind/kustomization.yaml
  config/apiserver/default/kustomization.yaml
  config/controller/default/kustomization.yaml
  config/default/apiserver/kustomization.yaml
  config/default/controller/kustomization.yaml
  config/kind/kustomization.yaml
  config/metalnetlet/default/kustomization.yaml
  config/metalnetlet/kind/kustomization.yaml
  docs/development/setup.md
Labels: documentation, size/L

#239 Fix release IP object when claimer NetworkInterface is deleted
  apinetlet/controllers/networkinterface_controller.go
  apinetlet/controllers/networkinterface_controller_test.go
Labels: bug, size/L
