Repository ironcore-dev/ironcore-net, pull requests merged in 2024-08, with the labels that each got.

#313 Fix watch setup in the `NetworkPolicy` reconciler of the `apinetlet`
  api/core/v1alpha1/network_types.go
  apinetlet/controllers/natgateway_controller.go
  apinetlet/controllers/networkpolicy_controller.go
  apinetlet/controllers/networkpolicy_controller_test.go
  client-go/openapi/zz_generated.openapi.go
  cmd/apinetlet/main.go
  cmd/controller-manager/main.go
  config/apinetlet/rbac/role.yaml
Labels: bug, size/M, ok-to-image

#314 Fix: use APINetClient for listing network policies for the network
  apinetlet/controllers/networkpolicy_controller.go
Labels: bug, size/XS

#315 Harmonize imports, func layout and log usage in `apinetlet` controllers
  apinetlet/controllers/loadbalancer_controller.go
  apinetlet/controllers/natgateway_controller.go
  apinetlet/controllers/network_controller.go
  apinetlet/controllers/networkinterface_controller.go
  apinetlet/controllers/networkpolicy_controller.go
  apinetlet/controllers/virtualip_controller.go
Labels: size/L, chore
