Repository ironcore-dev/ironcore-net, pull requests merged in 2025-06, with the labels that each got.

#412 Allow IP allocation from multiple `public-prefixes` of same IPFamily
  go.sum
  internal/apiserver/apiserver.go
  internal/app/app_suite_test.go
  internal/app/core_test.go
  internal/registry/ip/ipaddressallocator/ipaddressallocator.go
  internal/registry/ipallocator/ipallocator.go
Labels: bug, enhancement, size/L, area/iaas, area/networking

#416 Ignore `LoadBalancerRoutings` from other `Networks`
  metalnetlet/controllers/networkinterface_controller.go
  metalnetlet/controllers/networkinterface_controller_test.go
Labels: bug, size/L, area/iaas, area/networking

#418 Retain labels of apinet nic before setting claimer labels
  apinetlet/controllers/networkinterface_controller.go
  apinetlet/controllers/networkinterface_controller_test.go
Labels: bug, size/S, area/networking
