Repository ironcore-dev/ironcore-net, pull requests merged in 2025-03, with the labels that each got.

#384 Update reuse configuration
  .github/dependabot.yml
  REUSE.toml
Labels: size/S, chore

#369 Drop usage of kube-rbac-proxy
  cmd/apinetlet/main.go
  cmd/controller-manager/main.go
  cmd/metalnetlet/main.go
  config/apinetlet/certmanager/certificate-metrics.yaml
  config/apinetlet/certmanager/kustomization.yaml
  config/apinetlet/certmanager/kustomizeconfig.yaml
  config/apinetlet/default/cert_metrics_manager_patch.yaml
  config/apinetlet/default/kustomization.yaml
  config/apinetlet/default/manager_auth_proxy_patch.yaml
  config/apinetlet/default/manager_metrics_patch.yaml
  config/apinetlet/manager/manager.yaml
  config/apinetlet/prometheus/kustomization.yaml
  config/apinetlet/prometheus/monitor.yaml
  config/apinetlet/prometheus/monitor_tls_patch.yaml
  config/apinetlet/rbac/kustomization.yaml
  config/apinetlet/rbac/metrics_auth_role.yaml
  config/apinetlet/rbac/metrics_auth_role_binding.yaml
  config/apinetlet/rbac/metrics_reader_role.yaml
  config/apinetlet/rbac/metrics_service.yaml
  config/controller/certmanager/certificate-metrics.yaml
  config/controller/certmanager/kustomization.yaml
  config/controller/certmanager/kustomizeconfig.yaml
  config/controller/default/cert_metrics_manager_patch.yaml
  config/controller/default/kustomization.yaml
  config/controller/default/manager_auth_proxy_patch.yaml
  config/controller/default/manager_metrics_patch.yaml
  config/controller/manager/manager.yaml
  config/controller/prometheus/kustomization.yaml
  config/controller/prometheus/monitor.yaml
  config/controller/prometheus/monitor_tls_patch.yaml
  config/controller/rbac/kustomization.yaml
  config/controller/rbac/metrics_auth_role.yaml
  config/controller/rbac/metrics_auth_role_binding.yaml
  config/controller/rbac/metrics_reader_role.yaml
  config/controller/rbac/metrics_service.yaml
  config/metalnetlet/certmanager/certificate-metrics.yaml
  config/metalnetlet/certmanager/kustomization.yaml
  config/metalnetlet/certmanager/kustomizeconfig.yaml
  config/metalnetlet/default/cert_metrics_manager_patch.yaml
  config/metalnetlet/default/kustomization.yaml
  config/metalnetlet/default/manager_auth_proxy_patch.yaml
  config/metalnetlet/default/manager_metrics_patch.yaml
  config/metalnetlet/manager/manager.yaml
  config/metalnetlet/prometheus/kustomization.yaml
  config/metalnetlet/prometheus/monitor.yaml
  config/metalnetlet/prometheus/monitor_tls_patch.yaml
  config/metalnetlet/rbac/kustomization.yaml
  config/metalnetlet/rbac/metrics_auth_role.yaml
  config/metalnetlet/rbac/metrics_auth_role_binding.yaml
  config/metalnetlet/rbac/metrics_reader_role.yaml
  config/metalnetlet/rbac/metrics_service.yaml
Labels: enhancement, size/XXL

#386 Add mkdocs base documentation setup
  .github/workflows/publish-docs.yml
  Makefile
  REUSE.toml
  docs/Dockerfile
  docs/README.md
  docs/concepts/ip-lifecycle.md
  docs/concepts/ironcore-integration.md
  docs/concepts/network-lifecycle.md
  docs/concepts/objects.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, enhancement, size/L

#393 Bump golang to v1.24
  .github/workflows/lint.yml
  Makefile
  go.mod
Labels: size/XS, chore
